# Generated by Django 4.2.2 on 2023-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_texto', models.JSONField()),
                ('embeddings', models.JSONField()),
                ('nombre_archivo', models.CharField(default='S/N', max_length=100)),
                ('identificador', models.CharField(default='00000000000000000000', max_length=30)),
            ],
        ),
    ]
