# Generated by Django 4.2.2 on 2023-06-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reader_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='identificacion_unica',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
