# Generated by Django 4.2.2 on 2023-07-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_reader_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_id', to='api_reader_pdf.embedding'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
