# Generated by Django 4.2.2 on 2023-06-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reader_pdf', '0002_usuario_identificacion_unica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
