# Generated by Django 4.2.2 on 2023-06-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reader_pdf', '0004_delete_usedsession_remove_usuario_embedding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
