# Generated by Django 4.2.2 on 2023-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reader_pdf', '0005_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='nombre_archivo',
        ),
    ]
