# Generated by Django 4.2.2 on 2023-06-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reader_pdf', '0007_embedding_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='identificador',
            field=models.CharField(default='00000000000000000000', max_length=30),
        ),
    ]
