# Generated by Django 4.2.2 on 2023-06-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reader_pdf', '0009_historialchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialChat',
        ),
    ]
