# Generated by Django 4.2.2 on 2023-06-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='identificacion_unica',
        ),
    ]
