# Generated by Django 4.2.2 on 2023-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_usuario_identificacion_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='company',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
